"""Deterministic calculation and analysis tools package."""

from src.tools.decision_mapping import (
    DECISION_MEANINGS,
    DECISION_THRESHOLD_ACT,
    DECISION_THRESHOLD_ATTEND,
    DECISION_THRESHOLD_PLAN,
    DECISION_THRESHOLD_TRACK,
    DECISION_TO_REMEDIATION,
    DECISION_TO_RISK_TIER,
    ERS_MAX_SCORE,
    ERS_MIN_SCORE,
    AegisDecision,
    DecisionResult,
    get_decision_details,
    map_ers_to_decision,
    map_ers_to_remediation_decision,
    map_ers_to_risk_tier,
)
from src.tools.risk_config import (
    CONTROL_DISCOUNTS,
    CONTROL_MULTIPLIER_MAX,
    CONTROL_MULTIPLIER_MIN,
    CRITICALITY_SCORES,
    CVSS_BASE_SCALE,
    EXPOSURE_SCORES,
    SENSITIVITY_SCORES,
    THREAT_SCORE_KEV,
    THREAT_WEIGHT_EPSS,
    THREAT_WEIGHT_POC,
    TIER_THRESHOLD_CRITICAL,
    TIER_THRESHOLD_HIGH,
    TIER_THRESHOLD_LOW,
    TIER_THRESHOLD_MEDIUM,
    WEIGHT_BASE_CVSS,
    WEIGHT_ENV_CRITICALITY,
    WEIGHT_ENV_EXPOSURE,
    WEIGHT_ENV_SENSITIVITY,
    WEIGHT_ENVIRONMENTAL,
    WEIGHT_THREAT,
    determine_remediation_decision,
    determine_risk_tier,
)
from src.tools.risk_engine import (
    build_supporting_evidence,
    calculate_base_score,
    calculate_control_multiplier,
    calculate_environmental_score,
    calculate_ers,
    calculate_threat_score,
    calculate_weighted_risk,
    evaluate_risk,
    generate_risk_explanation,
)

__all__ = [
    # Calculation Functions
    "calculate_base_score",
    "calculate_threat_score",
    "calculate_environmental_score",
    "calculate_control_multiplier",
    "calculate_weighted_risk",
    "calculate_ers",
    "evaluate_risk",
    "generate_risk_explanation",
    "build_supporting_evidence",
    # Decision Mapping (Phase 3B)
    "AegisDecision",
    "DecisionResult",
    "map_ers_to_decision",
    "map_ers_to_risk_tier",
    "map_ers_to_remediation_decision",
    "get_decision_details",
    "DECISION_THRESHOLD_ACT",
    "DECISION_THRESHOLD_ATTEND",
    "DECISION_THRESHOLD_PLAN",
    "DECISION_THRESHOLD_TRACK",
    "ERS_MIN_SCORE",
    "ERS_MAX_SCORE",
    "DECISION_MEANINGS",
    "DECISION_TO_RISK_TIER",
    "DECISION_TO_REMEDIATION",
    # Configuration and Helpers
    "determine_risk_tier",
    "determine_remediation_decision",
    "TIER_THRESHOLD_CRITICAL",
    "TIER_THRESHOLD_HIGH",
    "TIER_THRESHOLD_MEDIUM",
    "TIER_THRESHOLD_LOW",
    "CVSS_BASE_SCALE",
    "WEIGHT_BASE_CVSS",
    "WEIGHT_THREAT",
    "WEIGHT_ENVIRONMENTAL",
    "WEIGHT_ENV_CRITICALITY",
    "WEIGHT_ENV_EXPOSURE",
    "WEIGHT_ENV_SENSITIVITY",
    "THREAT_SCORE_KEV",
    "THREAT_WEIGHT_EPSS",
    "THREAT_WEIGHT_POC",
    "CRITICALITY_SCORES",
    "EXPOSURE_SCORES",
    "SENSITIVITY_SCORES",
    "CONTROL_DISCOUNTS",
    "CONTROL_MULTIPLIER_MIN",
    "CONTROL_MULTIPLIER_MAX",
]
